{% set name = "catt" %}
{% set version = "0.12.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/catt-{{ version }}.tar.gz
  sha256: dbb024a1ed37705596db1f957bdeb99123eff26e724082fce23357367c458b73

build:
  entry_points:
    - catt = catt.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - click >=7.1.2
    - ifaddr >=0.1.7
    - pychromecast >=13.0.7,<14
    - requests >=2.23.0
    - yt-dlp >=2023.3.4

test:
  imports:
    - catt
  commands:
    - pip check
    - catt --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/skorokithakis/catt
  summary: Cast All The Things allows you to send videos from many, many online sources to your Chromecast.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
